# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'TV Programming Exercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TV Programming Exercise
  pod 'Alamofire', '~> 4.0'
  pod 'Kingfisher', '~> 5.15.7'
  pod 'PromiseKit', '~> 6.13.0'
  pod 'PromiseKit/Alamofire'
end
