# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Instacart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instacart
  pod 'SDWebImage'

  target 'InstacartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstacartUITests' do
    # Pods for testing
  end

end
